# Generated by Django 4.2.1 on 2023-05-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearcherResearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=2048)),
                ('name', models.CharField(max_length=256)),
                ('num_tokens', models.IntegerField()),
                ('embedding', models.CharField(max_length=4096)),
            ],
        ),
    ]
